# Generated by Django 4.2.5 on 2023-09-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_order_options_remove_order_quantity_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="product",
            new_name="products",
        ),
    ]
